### ISSUE TITLE
Error remedy unclear from documentation

### ISSUE THREAD

**Issue by allie-fowler** [tj-actions/docker-cp#52]
Hi there,

With the following action, I'm unclear as to why I'm getting the error "Error response from daemon: Could not find the file /home/pptruser/test.pdf in container <container id>"

```
  run_tests:
    needs: deploy-to-test-host
    runs-on: ubuntu-latest  # You can choose the appropriate runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: puppeteer-test
        uses: tj-actions/puppeteer@v4.1.0
        id: puppeteer-test
        with:
          files: |
            test/*.js
  
      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf
          destination: test.pdf

      - name: Display contents of test.pdf
        run: cat test.pdf 
```

Output:
```
Running test/*.js...
Completed executing test/*.js
0s
Run tj-actions/docker-cp@v2
  with:
    container: be7bd3e17c75
    source: /home/pptruser/test.pdf
    destination: test.pdf
    local: true
Run # Run docker cp
  # Run docker cp
  EXTRA_ARGS=
  
  if [ "true" != "true" ]; then
    docker cp $EXTRA_ARGS /home/pptruser/test.pdf be7bd3e17c75:test.pdf
  else
    docker cp $EXTRA_ARGS be7bd3e17c75:/home/pptruser/test.pdf test.pdf
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  
Error response from daemon: Could not find the file /home/pptruser/test.pdf in container be7bd3e17c75
Error: Process completed with exit code 1.
```

It's unclear from the documentation how to remedy?

**Comment by allie-fowler** [comment]
I see it now.  I had pulled the action code from your example, but the output file name was hard-coded into your test.js script.

**Comment by jackton1** [comment]
@allie-fowler  Yes that's correct you should replace the `source` and `destination` inputs with the file you want to copy from puppeteer container. The example test generates a [`test.pdf`](https://github.com/tj-actions/puppeteer/blob/main/test/test.js#L9) file

```yml
      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf  # <--- Replace me
          destination: test.pdf  # <--- Replace me

      - name: Display contents of test.pdf
        run: cat test.pdf  # <--- Replace me
```
